from django.urls import path
from . import views
app_name = 'warehouse'
urlpatterns = [
    path('good_in/category', views.GoodInCategoryListView.as_view(),
         name="good_in_category"),
    path('good_in/category/<int:category>',
         views.GoodInCategoryListView.as_view(), name="good_in_category"),
    path('category_good/create', views.CategoryGoodCreateView.as_view(),
         name="category_good_create"),
    path('good_service/<int:pk>/delete',
         views.CategoryGoodDeleteView.as_view(),
         name="category_good_delete"),
    path('good/search', views.GoodSearchView.as_view(),
         name="good_search"),
    path('good/create', views.GoodCreateView.as_view(),
         name="good_create"),
    path('good/<int:pk>/update',
         views.GoodUpdateView.as_view(),
         name="good_update"),
    path('good/<int:pk>/delete',
         views.GoodDeleteView.as_view(),
         name="good_delete"),
    path('storage/list', views.StorageListView.as_view(),
         name="storage_list"),
    path('storage_good/create', views.StorageCreateView.as_view(),
         name="storage_create"),
    path('storage_service/<int:pk>/delete',
         views.StorageDeleteView.as_view(), name="storage_delete"),
    path('operation/list', views.StorageOperationListView.as_view(),
         name="storage_operation_list"),
    path('arrival/good/create', views.ArrivalGoodFormView.as_view(),
         name="arrival_good_create"),
    path('write-off/good/create', views.WriteOffGoodFormView.as_view(),
         name="writeOff_good_create"),
    path('sale/good/create', views.SaleGoodFormView.as_view(),
         name="sale_good_create"),
]
