# Generated by Django 3.2.5 on 2021-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Доктор'), (3, 'Координатор')], default=1),
            preserve_default=False,
        ),
    ]
