# Generated by Django 3.2.5 on 2021-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_display_calendar',
            field=models.BooleanField(default=True),
        ),
    ]
