# Generated by Django 3.2.5 on 2022-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_display_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Регистратор'), (3, 'Доктор')], default=1),
        ),
    ]
