# Generated by Django 3.2.5 on 2022-02-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_speciality_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Больницы'},
        ),
    ]
