# Generated by Django 3.2 on 2023-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Регистратор'), (3, 'Доктор')], default=1),
        ),
    ]
