# Generated by Django 3.2.4 on 2023-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_code',
            field=models.CharField(default='Doctor Code', max_length=10, verbose_name='Doctor Code'),
        ),
    ]
