# Generated by Django 3.2.5 on 2022-02-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220209_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Мужчина'), ('woman', 'Женщина')], max_length=180, null=True),
        ),
    ]
