# Generated by Django 3.2.5 on 2022-01-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_speciality_company'),
        ('equipment_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_system.equipmentgroup'),
        ),
    ]
