# Generated by Django 3.2.5 on 2022-01-12 23:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_user_is_display_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
