# Generated by Django 3.2.5 on 2022-01-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('analytics', '0002_specialityanalytic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer.customer',),
        ),
    ]
