# Generated by Django 3.2.5 on 2022-01-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_schedule_status'),
        ('analytics', '0003_customeranalytic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAnalytic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('register.schedule',),
        ),
        migrations.CreateModel(
            name='ScheduleServiceAnalytic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('register.scheduleservice',),
        ),
    ]
