# Generated by Django 3.2.5 on 2021-12-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaidInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=0, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Терминал', 'Терминал'), ('KASPI RED', 'KASPI RED'), ('KASPI перевод', 'KASPI перевод'), ('Рассрочка', 'Рассрочка')], default='Наличные', max_length=80)),
                ('comment', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
    ]
