# Generated by Django 3.2.5 on 2021-12-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaidinvoice',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.schedule'),
        ),
    ]
