# Generated by Django 3.2.5 on 2021-12-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('comment', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('comment', models.TextField(blank=True)),
                ('barcode', models.CharField(max_length=180)),
                ('sale_unit', models.IntegerField(choices=[(1, 'штук'), (2, 'миллилитр'), (3, 'грамм'), (4, 'упаковка'), (5, 'миллиграмм'), (6, 'сантиметр'), (7, 'микролитр'), (9, 'сетр'), (10, 'рулон'), (11, 'литр'), (12, 'флакон'), (13, 'единица'), (14, 'килограмм'), (15, 'ампула'), (16, 'коробка'), (17, 'капсула'), (18, 'доза'), (19, 'другое')], default=0)),
                ('write_off_unit', models.IntegerField(choices=[(1, 'штук'), (2, 'миллилитр'), (3, 'грамм'), (4, 'упаковка'), (5, 'миллиграмм'), (6, 'сантиметр'), (7, 'микролитр'), (9, 'сетр'), (10, 'рулон'), (11, 'литр'), (12, 'флакон'), (13, 'единица'), (14, 'килограмм'), (15, 'ампула'), (16, 'коробка'), (17, 'капсула'), (18, 'доза'), (19, 'другое')], default=0)),
                ('unit_equals', models.IntegerField(default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('critical_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('desired_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.categorygood')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('comment', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('comment', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.IntegerField(choices=[(1, 'Приход товара'), (2, 'Перемещение товара'), (3, 'Списание товара'), (4, 'Продажа товара')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.provider')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageOperationGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('quantity_write_off', models.FloatField(default=1)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.good')),
                ('storage_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storageoperation')),
            ],
        ),
    ]
