# Generated by Django 3.2.5 on 2021-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20211218_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygood',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
