from django.urls import path
from . import views
app_name = 'work_time'
urlpatterns = [
    path('company/work_time_with_exclution',
         views.CompanyWorkTimeWithExclutionListView.as_view(),
         name="company_work_time_with_exclution_list"),
    path('user/work_time_with_exclution',
         views.UserWorkTimeWithExclutionListView.as_view(),
         name="user_work_time_with_exclution_list"),
    path('user/<int:pk>/work_time_with_exclution',
         views.UserWorkTimeWithExclutionListView.as_view(),
         name="user_work_time_with_exclution_list"),
    path('work_time_exclution/create',
         views.WorkTimeExclutionCreateView.as_view(),
         name="work_time_exclution_create"),
    path('company/work_time_exclution/create',
         views.CompanyWorkTimeExclutionCreateView.as_view(),
         name="company_work_time_exclution_create"),
    path('user/<int:pk>/work_time_exclution/create',
         views.UserWorkTimeExclutionCreateView.as_view(),
         name="user_work_time_exclution_create"),
    path('user/<int:pk>/work_time/create',
         views.UserWorkTimeCreateView.as_view(),
         name="user_work_time_create"),
    path('company/work_time/create',
         views.CompanyWorkTimeCreateView.as_view(),
         name="company_work_time_create"),
    path('company/work_time/list',
         views.CompanyWorkTimeListView.as_view(),
         name="company_work_time_list"),
    path('user/<int:pk>/work_time/list',
         views.UserWorkTimeListView.as_view(), name="user_work_time_list"),
    path('work_time/exclution/<int:pk>/delete',
         views.WorkTimeExclutionDeleteView.as_view(),
         name="work_time_exclution_delete"),
    path('work_time/<int:pk>/delete',
         views.WorkTimeDeleteView.as_view(), name="work_time_delete"),
    path('work_time/<int:pk>/update',
         views.WorkTimeUpdateView.as_view(), name="work_time_update"),
]
