# Generated by Django 3.2.5 on 2021-12-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('orientation', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='GroupForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, null=True)),
            ],
            options={
                'db_table': 'groupForms',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('label', models.TextField(blank=True, max_length=240, null=True)),
                ('kind', models.CharField(choices=[('text', 'Ввод текста'), ('textarea', 'textarea'), ('select', 'select'), ('parent', 'parent'), ('datalist', 'datalist'), ('mkb10', 'mkb10')], default='text', max_length=80)),
                ('colspan', models.CharField(max_length=80, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_italic', models.BooleanField(default=False)),
                ('is_center', models.BooleanField(default=False)),
                ('is_border', models.BooleanField(default=False)),
                ('is_rotated', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('grouping', models.CharField(blank=True, max_length=80, null=True)),
                ('group_separator', models.CharField(blank=True, max_length=80, null=True)),
                ('classes', models.CharField(blank=True, max_length=80, null=True)),
                ('rowspan', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'markers',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=15, null=True)),
                ('position', models.IntegerField(null=True)),
                ('classes', models.CharField(blank=True, max_length=80, null=True)),
                ('group', models.IntegerField(null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='document_circulation.form')),
            ],
            options={
                'db_table': 'rows',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReadyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_circulation.marker')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='document_circulation.readyphrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marker',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='document_circulation.row'),
        ),
        migrations.CreateModel(
            name='FuncStructureForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.funcstructure')),
                ('hospital_forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='func_struc_hosp_forms', to='document_circulation.companyform')),
            ],
        ),
        migrations.CreateModel(
            name='FormHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(null=True)),
                ('temporary_form_data', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_circulation.form')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('referer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_history_referers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companyform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_forms', to='document_circulation.form'),
        ),
        migrations.AddField(
            model_name='companyform',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_forms', to='document_circulation.groupform'),
        ),
        migrations.AddField(
            model_name='companyform',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.CreateModel(
            name='AdaptiveMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=180, null=True)),
                ('label', models.TextField(max_length=240, null=True)),
                ('options', models.TextField(null=True)),
                ('visible', models.CharField(max_length=80, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('func_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.funcstructure')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_circulation.marker')),
            ],
        ),
    ]
