# Generated by Django 3.2.5 on 2022-01-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='old_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
