# Generated by Django 3.2.5 on 2022-02-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_circulation', '0002_form_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='old_id',
        ),
    ]
