# Generated by Django 3.2.5 on 2022-02-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_circulation', '0006_alter_form_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcstructureform',
            name='hospital_forms',
        ),
        migrations.AddField(
            model_name='funcstructureform',
            name='company_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='func_struc_company_forms', to='document_circulation.companyform'),
            preserve_default=False,
        ),
    ]
