# Generated by Django 3.2.5 on 2022-02-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_circulation', '0007_auto_20220204_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyform',
            old_name='hospital',
            new_name='company',
        ),
    ]
