# Generated by Django 3.2.5 on 2022-02-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_circulation', '0008_rename_hospital_companyform_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcstructureform',
            name='company_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_circulation.companyform'),
        ),
    ]
