# Generated by Django 3.2.5 on 2021-12-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('equipment_system', '0001_initial'),
        ('service_system', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('duration', models.IntegerField(default=30)),
                ('status', models.IntegerField(choices=[(0, 'ожидание клиента'), (1, 'клиент пришел'), (2, 'клиент не пришел'), (3, 'клиент подтвердил')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimeExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'активный'), (1, 'не активный')], default=0)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('company', 'equipment', 'user')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(0, 'Пн'), (1, 'Втр'), (2, 'Срд'), (3, 'Чтв'), (4, 'Птн'), (5, 'Суб'), (6, 'Воск')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'не активный'), (1, 'активный')], default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('company', 'equipment', 'user')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'не выполнена'), (1, 'выполнена')], default=0)),
                ('status_payment', models.IntegerField(choices=[(0, 'не оплачено'), (1, 'оплачено')], default=0)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=60)),
                ('quantity', models.IntegerField(default=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.schedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_system.service')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_system.equipment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.schedule')),
            ],
        ),
    ]
