# Generated by Django 3.2.5 on 2021-12-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
