# Generated by Django 3.2.5 on 2022-01-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_schedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не подтвержден'), (1, 'Подтвержден'), (2, 'Выполнен'), (3, 'Неявка'), (4, 'Отменен')], default=0),
        ),
    ]
