# Generated by Django 3.2.5 on 2022-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_schedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleservice',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=60),
        ),
    ]
