# Generated by Django 3.2.5 on 2022-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_scheduleservice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидание клиента'), (1, 'Клиент пришел'), (2, 'Клиент не пришел'), (3, 'клиент подтвердил')], default=0),
        ),
    ]
