# Generated by Django 3.2.5 on 2022-01-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'активный'), (1, 'не активный')], default=0)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('company', 'equipment', 'user')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(0, 'Пн'), (1, 'Втр'), (2, 'Срд'), (3, 'Чтв'), (4, 'Птн'), (5, 'Суб'), (6, 'Воск')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'не активный'), (1, 'активный')], default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('company', 'equipment', 'user')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
