# Generated by Django 3.2.5 on 2021-12-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_amount', models.FloatField(default=0)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.good')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storage')),
                ('technological_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technological_card.technologicalcard')),
            ],
        ),
    ]
