# Generated by Django 3.2.4 on 2023-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internat_class_diseases', '0002_alter_mkb10_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
            ],
        ),
    ]
