from django.urls import path
from . import views
app_name = 'document_circulation'
urlpatterns = [
    path('form_in_history',
         views.WriteFormInHistoryView.as_view(), name='form_in_history'),
    path('form_in_history/<int:pk>',
         views.WriteFormInHistoryView.as_view(), name='form_in_history'),
    path('form_in_history/<int:pk>/<int:history>',
         views.WriteFormInHistoryView.as_view(), name='form_in_history'),
    path('form/create/<int:pk>/<int:form>',
         views.WriteFormInHistoryView.as_view(), name='form_create'),
    path('history/preview/pdf/<int:history>', views.HistoryPdfView.as_view(),
         name='history_pdf'),
    path('func_structure/form/list/<int:schedule>',
         views.FuncStructureFormListView.as_view(), name='func_structure_form_list'),
    path('history/delete/<int:pk>', views.HistoryDeleteView.as_view(),
         name='history_delete'),
    path('form/relation', views.FormRelationView.as_view(),
         name='form_relation'),
    path('marker/relation/<int:form>', views.MarkerRelationView.as_view(),
         name='marker_relation'),
    path('marker/relation/delete/<int:pk>',
         views.MarkerRelationDeleteView.as_view(),
         name='marker_relation_delete'),
    path('ready_phrase/<int:marker>',
         views.ReadyPhraseJsonView.as_view(),
         name='ready_phrase_json'),
    path('ready_phrase/create/<int:marker>',
         views.ReadyPhraseCreateView.as_view(),
         name='ready_phrase_create'),
    path('ready_phrase/update/<int:pk>',
         views.ReadyPhraseUpdateView.as_view(),
         name='ready_phrase_update'),
    path('ready_phrase/delete/<int:pk>',
         views.ReadyPhraseDeleteView.as_view(),
         name='ready_phrase_delete'),
    path('ready_phrase/list/<int:marker>',
         views.ReadyPhraseListView.as_view(), name='ready_phrase_list'),
    path('audio/text',
         views.AudioTextView.as_view(), name='audio_text'),
    path('admin/form/<int:pk>/detail', views.AdminFormDetail.as_view(),
         name='admin_form_detail'),
    path('examination/result/create', views.CreateExaminationResultView.as_view(),
         name='examination_result_create'),
]
